/*
Test Package: Semantic-1
Test Target: return
Author: Ruitian Wang
Time: 2025-08-26
Verdict: Fail
Comment: exit function test, unreachable code after exit() should cause compile-time error
*/

fn main() -> () {
    exit(1);
    println("unreachable");
}
